development:
  adapter: sqlite3
  database: db/backyarder-development

test:
  adapter: sqlite3
  database: db/backyarder-test

production:
  adapter: postgresql
  database: backyarder_ifmq
  username: backyarder_ifmq_user
  password: qfJVBysBRj9FKg7RqOLZ4BudllwJamDS
  host: postgres://backyarder_ifmq_user:qfJVBysBRj9FKg7RqOLZ4BudllwJamDS@dpg-ckaa1bugtj9c73afjqe0-a.oregon-postgres.render.com/backyarder_ifmq
  port: 5432
