development:
  adapter: sqlite3
  database: db/backyarder-development

test:
  adapter: sqlite3
  database: db/backyarder-test

production:
  adapter: postgresql
  database: backyarder_db_9c8v
  username: backyarder_db_9c8v_user
  password: SxIpT7w0btw8kuqvYfoJNL4zRXQhdJd5
  host: dpg-ckk4aibj89us739cmib0-a
  port: 5432
