development:
  adapter: sqlite3
  database: db/backyarder-development

test:
  adapter: sqlite3
  database: db/backyarder-test

production:
  adapter: postgresql
  database: d7b4h2udgt8lof
  username: thvwiironkprcm
  password: ced5159bf0e97f398837a83c235ec1a655658eaf5ab0fa49896bf60204cf48ee
  host: ec2-54-211-177-159.compute-1.amazonaws.com
  port: 5432
