development:
  adapter: sqlite3
  database: db/backyarder-development

test:
  adapter: sqlite3
  database: db/backyarder-test

production:
  adapater: postgresql
  database: backyarder
  username: username
  password: N0LYc3B2GVWxwY7RYiV3aQBru9L05FV8
  host: dpg-cjn5vllhe99c73bdg7s0-a